[package]
name = "singularity_perps_program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.18.26"
borsh = "0.10.3"
borsh-derive = "0.10.3"
thiserror = "1.0.56"
